# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67a6527e1279054294f39999ab5e83306d15cfba6788bbec36c26f873a9e9f692524cec26be7464cd1b368f1f9c1b741f1e8f6f43b89ffba23a72f817cdc5d13

test:
  secret_key_base: 108cbc683a43317cd4d22bd42858f80fd45e412042c33c942f8cce5a67c424056de3788822aa5076aaff5b44060bdb77da5b6d1b743ca613e3bfcad42ef70b7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
